import React from 'react';
import './SessionCompleted.css';

export default function SessionCompleted({ onGetFeedback }) {
    return (
        <div className="session-completed-container">
            <div className="session-completed-card">
                <div className="checkmark-icon">✓</div>
                <h1>Session Completed!</h1>
                <p>Your interview has been successfully submitted. Your detailed feedback report is being generated by the AI.</p>
                <button onClick={onGetFeedback} className="feedback-button">
                    View Detailed Feedback
                </button>
            </div>
        </div>
    );
}
