import React from 'react';
import './SessionCompleted.css';

export default function SessionCompleted({ onGetFeedback, status, errorMessage, onRetry, canViewFeedback }) {
    const normalizedStatus = status || 'not_requested';
    const isPending = normalizedStatus === 'pending' || normalizedStatus === 'processing';
    const isFailed = normalizedStatus === 'failed';

    return (
        <div className="session-completed-container">
            <div className="session-completed-card">
                <div className="checkmark-icon">✓</div>
                <h1>Session Completed!</h1>
                <p>Your interview has been successfully submitted. Your detailed feedback report is being generated by the AI.</p>
                {isPending ? (
                    <div className="session-completed-status" role="status" aria-live="polite">
                        <div className="session-completed-spinner" aria-hidden="true" />
                        <p className="session-completed-status-text">Finalizing your results… please wait.</p>
                    </div>
                ) : null}
                {isFailed && errorMessage ? (
                    <div className="session-completed-error" role="alert">
                        <p>{errorMessage}</p>
                        {onRetry ? (
                            <button type="button" className="session-completed-retry" onClick={onRetry}>
                                Regenerate Feedback
                            </button>
                        ) : null}
                    </div>
                ) : null}
                <button onClick={onGetFeedback} className="feedback-button" disabled={isPending || !canViewFeedback}>
                    {isPending ? 'Preparing report…' : 'View Detailed Feedback'}
                </button>
            </div>
        </div>
    );
}
